### ISSUE TITLE
[Feb 4th] Reinforcement Learning: An Introduction [meeting 1]

### ISSUE THREAD

**Issue by charlieegan3** [computationclub/computationclub.github.io#119]
**Date**: Feb 4th, 18:30-20:30

**Where**: [Ably, Techspace, 25 Luke St, London EC2A 4DS](https://www.google.com/maps/place/Ably+Realtime/@51.523993,-0.082597,15z/data=!4m2!3m1!1s0x0:0x8f615a6b0a356dc0?sa=X&ved=2ahUKEwiM2qnShJ_nAhVVRRUIHZ5lDXUQ_BIwE3oECBYQCA)

**What to read**:
_Book:_ Reinforcement Learning: An Introduction
_Section_: [Chapter 2.1](https://computationclub.slack.com/archives/C099DPD3L/p1579892232046000) (and as much of what comes before as you'd like)

Update: 2.1, 2.2 and 2.3 is the suggested reading.

Please react with a :+1: if you want to come.

**Comment by SimonWoolf** [comment]
> Meeting will be at: Ably?

Sure!

**Comment by charlieegan3** [comment]
Thanks! I've update the 'event'.

**Comment by charlieegan3** [comment]
Suggested reading now 2.1, 2.2 and 2.3

**Comment by charlieegan3** [comment]
Issue updated to show time... :man_facepalming:

**Comment by SimonWoolf** [comment]
We'll be in meeting room 6, in the basement. (Tell reception you're here for the Ably / Computation Club meeting in MR6 and they should let you in). That's the one with the sofas; we'll probably need to grab some seats from one of the other meeting rooms. (Or if we want we can move to one of the rooms with a big central table if people want -- few of them are ever in use this late)

**Comment by charlieegan3** [comment]
getting some image hosting for the wiki

![Image from iOS(5)](https://user-images.githubusercontent.com/1774239/73789390-9c3aff00-4796-11ea-8789-6968964d0d57.jpg)
![Image from iOS(4)](https://user-images.githubusercontent.com/1774239/73789391-9c3aff00-4796-11ea-9fe5-7b46eaa5f413.jpg)
![Image from iOS(3)](https://user-images.githubusercontent.com/1774239/73789394-9c3aff00-4796-11ea-8bfe-5b6b9bad64e1.jpg)
![Image from iOS(2)](https://user-images.githubusercontent.com/1774239/73789395-9cd39580-4796-11ea-84ed-144eb769e3f0.jpg)
![Image from iOS(1)](https://user-images.githubusercontent.com/1774239/73789396-9cd39580-4796-11ea-8a30-5c778201ae19.jpg)
![Image from iOS](https://user-images.githubusercontent.com/1774239/73789397-9cd39580-4796-11ea-8dde-cf3f52ddcf51.jpg)

**Comment by charlieegan3** [comment]
Further notes about the meeting, see here: https://github.com/computationclub/computationclub.github.io/wiki/Reinforcement-Learning:-An-Introduction-%5BMeeting-1%5D
