### ISSUE TITLE
Make it clear that people can join mid-book

### ISSUE THREAD

**Issue by mocoso** [computationclub/computationclub.github.io#25]
Perhaps it's just politeness but a number of people have said that they feel that they can't join in the middle of a book.

From my perspective, at least for the last two book projects, it has felt like most of the meetings did not require having been to all the previous one's for the book and so perhaps we should be explicit about this.

**Comment by mudge** [comment]
Since this was raised, we've tried to accommodate people joining mid-book either through picking books more amenable to joining partway through (e.g. NTO, 7ML7W) or by having explicit non-book interstitial meetings. As we're not currently reading a book at all, going to close this for now.
