### ISSUE TITLE
Organise next meeting

### ISSUE THREAD

**Issue by cwrw** [computationclub/computationclub.github.io#71]
### As soon as you're assigned

- [x] Assign yourself this issue! (If you're not a member of [London Computation Club](https://github.com/computationclub) on GitHub, ask someone on Slack to add you.)
- [x] Make sure you have access to the [Buffer](http://buffer.com) account for the club - this is how you'll tweet. (Ask on #general in Slack and someone will DM you the credentials.)
- [x] Make sure you can commit to the Computation Club website repository

### The next day

- [x] Remove the previous meeting’s proposal from the #votes Slack channel (or ask the author of the message to remove it)
- [x] Remove the previous meeting’s chapter from Slack (if scanned; you may need a Slack admin user to do this)
- [x] Encourage a write up of the previous meeting in Slack
- [x] Add a link to the previous meeting’s write up to the: 
  * [x] [wiki homepage](https://github.com/computationclub/computationclub.github.io/wiki/Home/_edit)
  * [x] [wiki sidebar](https://github.com/computationclub/computationclub.github.io/wiki/_Sidebar/_edit)
  * [x] [meetings.yml file](https://github.com/computationclub/computationclub.github.io/edit/master/_data/meetings.yml)
- [x] Announce the write-up!
  * [x] Slack
  * [x] The mailing list
  * [x] Twitter

### Same day / A few days later (but not too long!)

- [x] Double check that someone (Leo or Dan) at Geckoboard is able to host on the planned date; if not:
  * [x] Make a Doodle poll with potential dates
  * [x] Announce the poll on Slack
  * [x] Announce the poll on the mailing list
  * [x] Announce the poll on Twitter
  * [x] Pick a date
- [x] Identify the next chapter(s) to read for the next meeting
- [x] Create an online event using an appropriate service that allows us to measure attendance.  We prefer to add it to [Attending.io](https://attending.io) as Lanyrd is too unreliable.
- [x] Announce the meeting!
  * [x] Slack
  * [x] The [mailing list](https://groups.google.com/forum/#!forum/london-computation-club)
  * [x] Twitter
- [x] Add the next meeting to the Computation Club website by [editing the meetings.yml file](https://github.com/computationclub/computationclub.github.io/edit/master/_data/meetings.yml). Make sure your YAML is well-formatted - don't leave any colons in titles, for example!
- [x] Try to get a copy of the chapter scanned and put it on Slack as a single .pdf file ([Office Lens](https://itunes.apple.com/gb/app/office-lens/id975925059?mt=8) app might be useful to "scan" chapters with your phone)

### A day or two before the meeting

- [x] Remind people about the next meeting
  * [x] Slack
  * [x] The [mailing list](https://groups.google.com/forum/#!forum/london-computation-club)
  * [x] Twitter
- [x] [Update the meeting checklist template](https://github.com/computationclub/computationclub.github.io/wiki/Meeting-checklist-template/_edit) based on your experiences using it. Maybe we've missed something, or the timings need to be improved?
- [x] Copy [the source of meeting checklist template](https://github.com/computationclub/computationclub.github.io/wiki/Meeting-checklist-template/_edit) to a new issue, called "Organise next meeting".

### At the meeting

- [x] Pick an organizer for the next meeting

### Finally

- [x] Mark this issue as done! Excellently executed!

**Comment by mudge** [comment]
Made a Doodle poll for the next meeting: https://doodle.com/poll/wr6vhsektw2wm5f8
